#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  4 14:54:19 2024

@author: marwakasim
"""

import pandas as pd

data = {
    "Modulbeskrivelser": [
        "Den studerende kan med udgangspunkt i børn, unge og voksnes forudsætninger og perspektiver etablere, vurdere og evaluere pædagogiske miljøer og aktiviteter, der understøtter børn, unge og voksnes udvikling, samt i relation til dette redegøre for faglige vurderinger og valg.", 
        "Den studerende kan med udgangspunkt i børn, unge og voksnes forudsætninger og perspektiver etablere, vurdere og evaluere pædagogiske miljøer og aktiviteter, der understøtter børn, unge og voksnes udvikling, samt i relation til dette redegøre for faglige vurderinger og valg.",
        "Den studerende kan med udgangspunkt i børn, unge og voksnes forudsætninger og perspektiver etablere, vurdere og evaluere pædagogiske miljøer og aktiviteter, der understøtter børn, unge og voksnes udvikling, samt i relation til dette redegøre for faglige vurderinger og valg.",
        "Den studerende kan fagligt begrunde pædagogisk arbejde i relation til den samfundsmæssige, historiske, institutionelle og professionelle sammenhæng",
        "Den studerende kan fagligt begrunde pædagogisk arbejde i relation til den samfundsmæssige, historiske, institutionelle og professionelle sammenhæng",
        "Den studerende kan fagligt begrunde pædagogisk arbejde i relation til den samfundsmæssige, historiske, institutionelle og professionelle sammenhæng.",
        "Den studerende kan anvende natur samt kulturelle medier og udtryksformer til at skabe udviklings- og læreprocesser for 0- 5 årige børn samt inddrage børns perspektiv, deres kreativitet og leg i pædagogiske aktiviteter.",
        "Den studerende kan anvende natur samt kulturelle medier og udtryksformer til at skabe udviklings- og læreprocesser for 0- 5 årige børn samt inddrage børns perspektiv, deres kreativitet og leg i pædagogiske aktiviteter. Den studerende kan reflektere, vurdere, begrunde og kvalificere pædagogisk arbejde på baggrund af de organisatoriske og professionelle rammer.",
        "Den studerende kan reflektere, vurdere, begrunde og kvalificere pædagogisk arbejde på baggrund af de organisatoriske og professionelle rammer",
        "Den studerende kan med inddragelse af pædagogiske og didaktiske teorier tilrettelægge, gennemføre og analysere pædagogiske aktiviteter, inkluderende læringsmiljøer, lærings- og under- visningsforløb med henblik på, at børn og unges trivsel, læring, udvikling og dannelse fremmes.",
        "Den studerende kan med inddragelse af pædagogiske og didaktiske teorier tilrettelægge, gennemføre og analysere pædagogiske aktiviteter, inkluderende læringsmiljøer, lærings- og undervisningsforløb med henblik på, at børn og unges trivsel, læring, udvikling og dannelse fremmes.",
        "Den studerende kan varetage og analysere pædagogisk arbejde, der støtter og faciliterer børn og unges læring, udvikling, inklusion, trivsel og perspektiver.",
        "Den studerende kan med udgangspunkt i de tre målgruppers forudsætninger og perspektiver identificere og varetage pædagogiske opgaver i relation hertil. Den studerende har indsigt i social- og specialpædagogiske paradigmer, vidensformer og metoder.",
        "Den studerende kan med udgangspunkt i de tre målgruppers orudsætninger og perspektiver identificere og varetage pædagogiske opgaver i relation hertil. Den studerende har indsigt i social- og specialpædagogiske paradigmer, vidensformer og metoder.",
        "Den studerende kan tilrettelægge, gennemføre og evaluere social- og specialpædagogiske indsatser og aktiviteter, der sigter mod at fremme trivsel og livskvalitet, og som understøtter de tre målgruppers udvikling, læreprocesser og deltagelse i fællesskaber.",
        "Den studerende kan identificere, analysere og reflektere over tværprofessionelle og tværsektorielle dilemmaer og potentialer og skal indgå i, koordinere og lede helhedsorienterede og tværgående samarbejdsprocesser.",
        "Den studerende kan skabe rammer for, lede og udvikle kreative erfarings- og læreprocesser, som understøtter og inspirerer mennesker til at arbejde kreativt med musiske og æstetiske udtryksformer og kulturskabende virksomhed.",
        "Den studerende kan skabe rammer for, lede og udvikle pædagogiske forløb med et naturvidenskabeligt udgangspunkt og med fokus på børn, unge og voksnes naturoplevelser, natur forståelse med uderummet som læringsmiljø.",
        "Den studerende kan igangsætte, gennemføre og lede sundhedsfremmende og bevægelsesmæssige aktiviteter og ud- viklingsprocesser, der understøtter menneskers sundhed, livskvalitet og trivsel og motiverer til kropslig udfoldelse",
        "Den studerende kan etablere, udvikle og lede pædagogiske processer og produktioner ved anvendelse af digitale medier.",
        "Den studerende kan udvikle, iværksætte og lede kulturprojekter, som sigter mod menneskers inddragelse og deltagelse i og med produktion af kulturliv.",
        "Den studerende kan udfordre eksisterende og udvikle nye pædagogiske praksisser og organisationsformer, der bidrager til at håndtere udfordringer og nytænkning inden for pædagogprofessionen.",
        "Den studerende kan reflektere over og handle i forhold til kulturforskelle, kulturmøder og kulturkonflikter samt inddrage kulturdiversitet som et deltagerperspektiv og en ressource i pædagogisk praksis.",
        "De studerende kan begrunde, tilrettelægge, gennemføre og evaluere pædagogiske aktiviteter gennem deltagelse i pædagogisk prak- sis på praktikstedet, herunder vurdere egne læreprocesser i praksis.",
        "Den studerende kan skabe relationer til det enkelte barn og børnegruppen, støtte børnene i at indgå i relationer til hinanden, støtte udviklingen af børns kommunikative kompetencer, beherske professionel kommunikation samt reflektere over sine egne evner til at kommunikere og indgå i relationer.",
        "Den studerende skal målrettet kunne tilrettelægge, gennemføre, dokumentere og evaluere aktiviteter og læreprocesser, der støtter barnets trivsel, læring, dannelse og udvikling. I den forbindelse skal den studerende på et fagligt grundlag kunne udfordre eksisterende praksis, afsøge og vurdere alternative muligheder og bidrage til udvikling af pædagogisk praksis.",
        "Den studerende kan skabe sammenhænge mellem forskellige udviklings- og læringsrum og varetage pædagogiske og didaktiske opgaver i fritidstilbud og skole samt indgå i professionel kommunikation herom.",
        "Den studerende kan arbejde tværprofessionelt med udvikling af skole- og fritidspædagogik, så børn og unges trivsel, udvikling og læring fremmes.",
        "Den studerende kan kommunikere professionelt i relation til målgruppen og kolleger og kan på den baggrund gennemføre pædagogiske aktiviteter på et etisk forsvarligt grundlag.",
        "Den studerende kan gennem udvikling af pædagogisk praksis understøtte de tre målgruppers lærings-, udviklings- og omsorgsbehov og perspektiver i samarbejde med relevante aktører.",
        "Den studerende kan identificere, undersøge, udvikle og perspektivere pædagogfaglige problemstillinger."
        "Den studerende kan redegøre for udvalgte teorier og værdier og reflektere over den pædagogiske opgave med at under- støtte børn, unge og voksnes udvikling. Den studerende kan på baggrund af egne praktiske/æstetiske erfaringer demonstrere færdigheder i og viden om tilrettelæggelse, gennemførelse og evaluering af udvalgte aktiviteter med børn, unge eller voksne. Den studerende kan redegøre for børn, unge og voksnes forskellige forudsætninger og for egne faglige vurderinger og valg.",
        "Den studerende har viden om og færdigheder i at anvende et tværfagligt socialpsykologisk og sociologisk praksisrettet perspektiv på relationerne mellem faktorer, der generelt påvirker og muliggør børns, unges og voksnes udvikling, læring, identitet og dannelse og særligt har betydning for deres kønsidentitet, seksualitet og familieformer. Den studerende har viden om og færdigheder i, at etablere ud- viklende, lærerige og dannende pædagogiske miljøer og professionelle omsorgsrelationer i pædagogisk praksis baseret på børns, unges og voksnes perspektiver på ligestilling og mangfoldighed set i relation til deres familieformer og køn",
        "Den studerende kan redegøre for og reflektere over, hvordan inkluderende pædagogiske miljøer skaber betingelser for børns, unges og voksnes individuelle og sociale trivsel og udvikling. Den studerende har viden om sprogets betydning, og kan understøtte sprogudvikling og fremme kommunikationskompetencer. Den studerende kan på baggrund af egne praktiske/æstetiske erfaringer planlægge, gennemføre og evaluere pædagogiske aktiviteter i forhold til en målgruppe i et pædagogisk miljø og anvende teorier og metoder til at redegøre for egne faglige vurderinger og valg.",
        "Den studerende kan redegøre for og reflektere over den myndighed pædagogen repræsenterer i pædagogisk praksis, her- under praksis’ juridiske grundlag i relation til tavshedspligt og underretning. Den studerende kan identificere og fagligt begrunde gennem- førelse af tidlig pædagogisk indsats, forebyggende og sundhedsfremmende tiltag i pædagogisk praksis. Den studerende kan varetage professionelle samtaler med børn, unge, voksne, pårørende og myndigheder herunder redegøre for og reflektere over indhold, virkemidler og dilemmaer.",
        "Den studerende kan redegøre for viden om velfærdsamfundets og det pædagogiske arbejdes udvikling i en historisk kontekst. Den studerende kan redegøre for og reflektere over, hvordan pædagogiske miljøer og aktiviteter kan udvikle og fremme medborgerskab og demokratisk dannelse og på baggrund heraf tilrettelægge og varetage pædagogiske aktiviteter i samarbejde med relevante parter. Den studerende kan analysere samskabelse på tværs af professioner, institutioner og organisationer i det pædagogiske felt og kan reflektere, vurdere og perspektivere eget projekt ind i denne ramme.",
        "Den studerende kan fremstille sammenhænge mellem pædagogiske paradigmer og pædagogers handlemuligheder. Den studerende kan analysere og vurdere professionsetiske dilemmaer og værdier i pædagogisk praksis.Den studerende kan reflektere over forudsætninger og vilkår for pædagogers professionelle dømmekraft og vurdere pædagogers samfundsopgave og egen rolle i relationelt arbejde.",
        "Den studerende kan på et pædagogisk grundlag undersøge, udvikle og skabe pædagogiske og æstetiske processer i dag- institutionens hverdagsliv, der understøtter 0-5 årige børns deltagelsesmuligheder, trivsel, dannelse, leg, læring og udvikling – med inddragelse af børnegruppens mangfoldighed og ressourcer.",
        "Den studerende kan på et forskningsinformeret og professionsfagligt grundlag lede og udvikle pædagogiske læringsmiljøer og skabe en evalueringskultur, hvor pædagogisk dokumentation og evaluering indgår meningsfuldt i analyser af sammenhængen mellem pædagogisk praksis, det samlede læringsmiljø og børns trivsel, dannelse, læring og udvikling i historisk og aktuelt perspektiv. Vurdere og håndtere professionsetiske problemstillinger og etiske dilemmaer i pædagogisk praksis ud fra såvel læreplanens børnesyn som børns egne perspektiver.",
        "Den studerende kan redegøre for og reflektere over dagtilbuddets samfundsmæssige roller og opgaver – også̊ i forhold til børn i udsatte positioner – samt analysere, forstå̊ og vurdere dagtilbuddets praksisser på et pædagogisk og professionsetisk grundlag. Den studerende har viden om organisatoriske og professionelle rammers betydning for udvikling af professionsfaglige fællesskaber og kan bidrage til udvikling af disse – også i dialog og samarbejde med andre professioner, forældre, frivillige og civilsamfund inden for det gældende retsgrundlag. Den studerende kan analysere og vurdere dagtilbuddenes organisatoriske og professionelle rammer– herunder ledelsesmæssige forhold, den konkrete organisering og strukturering af hverdagslivet i institutionen, samt organisationskulturens betydning for udøvelsen af den pædagogiske praksis. Den studerende kan undersøge, udvikle og indgå i faglige dia- loger om det pædagogiske og vidensmæssige grundlag for dagtilbuddets pædagogiske læringsmiljø, herunder anvende videnskabelige metoder til undersøgelse, udvikling og kvalificering af pædagogisk praksis.",
        "Den studerende kan redegøre, analysere og reflektere over børns og unges forskellige forudsætninger for trivsel, udvikling, læring og dannelse. Den studerende kan redegøre for og reflektere over hvordan for- skellige pædagogiske aktiviteter kan understøtte undervisning, udvikling og læring. Den studerende kan udvikle, gennemføre og vurdere didaktisk tilrettelæggelse af undervisningsforløb og pædagogiske aktiviteter med henblik på børns og unges læring, dannelse, fællesskaber og udvikling i skole og fritidstilbud.",
        "Den studerende kan anvende andres og egen systematiske vidensindsamling med henblik på at kvalificere vidensgrundlaget i pædagogisk praksis. Den studerende kan anvende systematisk indsamlet viden i målrettet didaktisk planlægning, gennemførelse, dokumentation og evaluering af pædagogisk praksis, herunder professionsetiske problemstillinger knyttet til dette. Den studerende kan reflektere over og etisk ansvarligt an- vende forskellige undersøgelsesmetoder, der undersøger og udvikler pædagogisk praksis’ vidensgrundlag.",
        "Den studerende kan redegøre for og reflektere over forskellige perspektiver på børns og unges identitetsdannelse og socialisering. Den studerende kan varetage og analysere pædagogisk arbejde, der støtter og faciliterer børns og unges leg, læring, ud- vikling, inklusion og trivsel og reflektere over alternative handlemuligheder. Den studerende kan tilrettelægge og reflektere over forældre- samarbejde med udgangspunkt i det enkelte barns eller den enkelte unges trivsel, læring og udvikling. Den studerende kan analysere og vurdere det vidensgrundlag der ligger til grund for pædagogisk praksis, herunder anvende videnskabelige metoder til undersøgelse og udvikling af pædagogisk praksis.",
        "Den studerende kan redegøre og reflektere over viden om mennesker i udsatte positioner i samfundsmæssige sammenhænge og centrale teorier, begreber og metoder i pædagogisk og socialt arbejde med mennesker i udsatte positioner. Den studerende kan anvende centrale teorier og begreber til at identificere og analysere problemstillinger vedrørende menne- sker i udsatte positioner i konkrete pædagogiske og sociale sammenhænge. Den studerende kan fagligt begrunde handleforslag i forhold til pædagogiske og sociale indsatser for og med mennesker i ud- satte positioner.",
        "Den studerende kan redegøre for, analysere og håndtere den social- og specialpædagogisk aktuelle praksis ud fra et historisk perspektiv. Den studerende kan anvende forskningsbaseret viden i analyser og vurderinger, der understøtter udvikling, læring og livsbetingelser blandt mennesker i udsatte positioner. Den studerende kan udvikle social- og specialpædagogisk praksis gennem håndtering af professionsetik i relation til egne og andres undersøgelser af social- og specialpædagogisk praksis",
        "Den studerende kan redegøre for og reflektere over perspektiver på individets, gruppers og fællesskabers forudsætninger, behov, ressourcer og rammebetingelser. Den studerende kan analysere og vurdere forskellige rammebetingelsers betydning for menneskers udvikling. Den studerende kan tilrettelægge, gennemføre og evaluere social- og specialpædagogiske indsatser og inddrage udvalgte udtryksformer, fagligt begrunde sine valg og reflektere over alternative måder at handle på i pædagogisk praksis. Den studerende kan analysere og vurdere det vidensgrundlag, der ligger til grund for pædagogisk praksis, herunder anvende videnskabelige metoder til undersøgelse og udvikling af pædagogisk praksis.",
        "Den studerende kan redegøre for og reflektere over egen faglighed og faglige identitet i relation til andre faggruppers professionsforståelse, faglighed og traditioner. Den studerende kan identificere og analysere muligheder og barrierer i tværprofessionelt samarbejde og perspektivere til den politiske og juridiske kontekst samt vurdere etiske dilemmaer. Den studerende kan analysere tværprofessionel projektorganise- ring og varetage procesledelse i en innovativ og samskabende proces, der tager højde for borgeres interesser, behov og rettigheder gennem inddragelse af forskellige interessenter som fri- villige, foreninger samt offentlige og private organisationer og virksomheder.",

  ]
}



#df
df = pd.DataFrame(data)

#save as csv
csv_file_path = '/Users/marwakasim/Desktop/modulbeskrivelser_new.csv'
df.to_csv(csv_file_path, index=False)






